Repository LETMIN-Corp/letmin-client, pull requests merged in 2022-09, with the labels that each got.

#71 Private Routes loop fix and Company Login and Register
  package-lock.json
  src/App.tsx
  src/Assets/loading.gif
  src/Components/Buttons/FormButton.tsx
  src/Components/Inputs/TextInput.tsx
  src/Context/AuthContextProvider.tsx
  src/Context/AuthReducer.tsx
  src/Context/Types.tsx
  src/Routes/PublicRoutes.tsx
  src/Views/Admin/AdminCompany.tsx
  src/Views/Admin/AdminLogin.tsx
  src/Views/Company/CompanyLogin.tsx
  src/Views/Company/CompanyProfile.tsx
  src/Views/Company/CompanyRegister.tsx
  src/Views/Loading.tsx
  src/Views/Register.tsx
Labels: enhancement, help wanted

#79 User blocking
  src/Contexts/AuthContextProvider.tsx
  src/Utils/useAdmin.tsx
  src/Views/Admin/AdminCollaborator.tsx
Labels: enhancement

#85 Company profile
  src/Contexts/AuthContextProvider.tsx
  src/Utils/useCompany.tsx
  src/Views/Company/CompanyProfile.tsx
Labels: enhancement

#84 get Users
  src/Components/Cards/CompanySearchCard.tsx
  src/Contexts/AuthContextProvider.tsx
  src/Utils/useCompany.tsx
  src/Views/Company/CompanyTalentSearch.tsx
Labels: help wanted

#87 Profile data, picture, formations and experiences WIP
  src/App.tsx
  src/Assets/user_default.jpg
  src/Components/Cards/UserExperienceCard.tsx
  src/Components/Inputs/TextAreaInput.tsx
  src/Components/Modals/BigFormModal.tsx
  src/Contexts/AuthContextProvider.tsx
  src/Utils/useUser.tsx
  src/Views/User/UserEditData.tsx
  src/Views/User/UserProfle.tsx
  src/index.css
Labels: bug, enhancement
